[tool.black]
line_length = 100
exclude = '(\.git|\.mypy_cache|venv)'
target_version = ['py310']

[tool.isort]
py_version = 310
virtual_env = "venv"
line_length = 100
combine_as_imports = true
reverse_relative = true
lines_after_imports = 2
# Black-compatible isort configuration
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
